### PR TITLE
Html forms

### PR DESCRIPTION
**Pull request by PhiPhiPhi**
Html forms project done. Please review

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
## Hi team! image
Great job! Wow, your README is very detailed. Love the effort you have put in. 
Looks really image


#### Your project did not pass the linter check. image
[OPTIONAL] Friendly advice make your commits messages meaningful read more here  =>  [How to make your commit messages awesome and keep your team happy](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8/)

##### Page structure

###### Intuit products

* [x] It shows the Mint logo and text (logo on the left, text on the right).
* [x] It shows the Quickbooks logo and text (logo on the left, text on the right).
* [x] It shows the Turbotax logo and text (logo on the left, text on the right).
###### How it should look like :

mint


#### Files not related to the project should not be commited and added to .gitignore

#### To be sure that basic CSS bad practices are not used please read ([article for support ](https://speckyboy.com/good-bad-css-practices))
* [x] No repeat of the same rule (font-family: AvenirNext, Avenir, "Helvetica Neue", Helvetica, Arial, sans-serif;)


            body {
                    background: #eceef1;
                    font-family: AvenirNext, Avenir, "Helvetica Neue", Helvetica, Arial, sans-serif;
              }
So you can delete this property from

             #account_notice {
                     display: flex;
                     flex-direction: column;
                     margin-right: 15px;
                     font-size: 12px;
                     line-height: 1.5;
                     text-align: right;
               }

* [x] Great that you use the [`<main>` tag](https://www.w3schools.com/tags/tag_main.asp) for the dominant content of the `<body>` of a document
and the [`<footer>`](https://www.w3schools.com/TagS/tag_footer.asp) tag for the footer
* [x] Also good practice to use the [`<nav>` tag](http://html5doctor.com/nav-element/) for the major navigation links

***Please makes changes and submit another review request. 

If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email .***
Happy coding image

**Comment by dannkkie** [comment]
Thank you for the compliment and critique will make changes and push for review

**Review by Forison — COMMENTED** [review]
# Pull request under review by Addo

**Review by Forison — APPROVED** [review]
# Good Job team 
you have successfully 👌 implemented the changes suggested by my colleague earlier 
#### Go ahead and merge to master💪
## Project is approved👌
Happy coding

**Comment by dannkkie** [comment]
Awesome thanks so much

**Pull request merged**
